In [7]:
import pandas as pd
import ast

In [8]:
df = pd.read_excel("df_sampled.xlsx")

In [9]:
df.head()

,price,description,location,type,bathrooms,available_from,payment_method,size_sqm,bedrooms_count,has_maid_room,property_images
0,16000000,Code Dina-VRS2\nCompound name : Villette\nUnit...,"Villette, 5th Settlement Compounds, The 5th Se...",Apartment,3,2025-09-01 00:00:00,Cash,190,3,0,['https://media.rightmove.co.uk/113k/112651/16...
1,4100007,Apartment for sale in Al Burouj Compound\nBalk...,"Al Burouj Compound, El Shorouk Compounds, Shor...",Apartment,3,2025-09-02 00:00:00,Cash,150,3,0,['https://media.rightmove.co.uk/272k/271223/15...
2,4600000,For Sale: Exceptional Ready-to-Move-In Apartme...,"Madinaty, Cairo",Apartment,1,2025-08-28 00:00:00,Cash,91,2,0,['https://media.rightmove.co.uk/49k/48928/1601...
3,2000000,"Studio for sale in Sheraton Plaza\n3rd floor, ...","Sheraton Rd, Hurghada, Red Sea",Apartment,1,2025-09-02 00:00:00,Cash,43,3,0,['https://media.rightmove.co.uk/291k/290954/16...
4,5993079,Resale | Apartment for Sale in Eliva – Mostakb...,"Aliva, Mostakbal City Compounds, Mostakbal Cit...",Apartment,3,2025-08-31 00:00:00,Installments,120,2,0,['https://media.rightmove.co.uk/137k/136148/16...

In [10]:
df.rename(columns={"property_images":"photos_url"}, inplace=True)

In [11]:
df["photos_url"] = df["photos_url"].apply(ast.literal_eval)

In [5]:
df.head()

,price,description,location,type,bathrooms,available_from,payment_method,size_sqm,bedrooms_count,has_maid_room,photos_url
0,16000000,Code Dina-VRS2\nCompound name : Villette\nUnit...,"Villette, 5th Settlement Compounds, The 5th Se...",Apartment,3,2025-09-01 00:00:00,Cash,190,3,0,['https://media.rightmove.co.uk/113k/112651/16...
1,4100007,Apartment for sale in Al Burouj Compound\nBalk...,"Al Burouj Compound, El Shorouk Compounds, Shor...",Apartment,3,2025-09-02 00:00:00,Cash,150,3,0,['https://media.rightmove.co.uk/272k/271223/15...
2,4600000,For Sale: Exceptional Ready-to-Move-In Apartme...,"Madinaty, Cairo",Apartment,1,2025-08-28 00:00:00,Cash,91,2,0,['https://media.rightmove.co.uk/49k/48928/1601...
3,2000000,"Studio for sale in Sheraton Plaza\n3rd floor, ...","Sheraton Rd, Hurghada, Red Sea",Apartment,1,2025-09-02 00:00:00,Cash,43,3,0,['https://media.rightmove.co.uk/291k/290954/16...
4,5993079,Resale | Apartment for Sale in Eliva – Mostakb...,"Aliva, Mostakbal City Compounds, Mostakbal Cit...",Apartment,3,2025-08-31 00:00:00,Installments,120,2,0,['https://media.rightmove.co.uk/137k/136148/16...

In [12]:
df.to_json("sampled_properties.jsonl", orient="records", lines=True)